### ISSUE TITLE
"Missing required config: `region`" error after upgrade to 0.3.0

### ISSUE THREAD

**Issue by HusseinMorsy** [ember-cli-deploy/ember-cli-deploy-lightning-pack#15]
After upgrade ember-cli-deploy-lightning-pack  from version 0.2.0 to 0.3.0 in package.json
```diff
     "ember-cli-deploy": "0.5.1",
-    "ember-cli-deploy-lightning-pack": "0.2.0",
+    "ember-cli-deploy-lightning-pack": "0.3.0", 
```
I got the following error trace, when running `ember deploy prod`
```
- Missing required config: `region`
Error: Missing required config: `region`
Error: Missing required config: `region`
    at Class.CoreObject.extend.ensureConfigPropertySet (/Users/demo/project/node_modules/ember-cli-deploy-plugin/index.js:41:13)
    at Array.forEach (native)
    at Class.CoreObject.extend.configure (/Users/demo/project/node_modules/ember-cli-deploy-plugin/index.js:23:19)
    at Object._pipeline.register.fn (/Users/demo/project/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:175:21)
    at Pipeline._notifyPipelinePluginHookExecution (/Users/demo/project/node_modules/ember-cli-deploy/lib/models/pipeline.js:136:19)
    at lib$rsvp$$internal$$tryCatch (/Users/demo/project/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/demo/project/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/demo/project/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/demo/project/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:433:9)Pipeline aborted
```

**Comment by ghedamat** [comment]
@HusseinMorsy that is correct

https://github.com/ember-cli-deploy/ember-cli-deploy-s3/releases/tag/v0.2.0 had a breaking change and now `region` is a required property

this is why the lightning pack got updated from 0.2.X to 0.3.X, following `semver` this  is denoting a breaking change (in the pre 1.X series)

all you should need to do is set region to `us-east-1` if you want to get the old default.

Let us know if you see other problems!

**Comment by HusseinMorsy** [comment]
@ghedamat many  thanks for your help.  After I put `ENV.s3.region = 'us-east-1';` to my config/deploy.rb it's now working
